name: cross compile

on: push

jobs:
  build-x86_64-pc-windows-gnu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cross
        run: cargo install cross
      - name: Cross compile for x86_64-pc-windows-gnu
        run: cross build --features windows-build --target x86_64-pc-windows-gnu
  build-x86_64-unknown-linux-gnu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cross
        run: cargo install cross
      - name: Cross compile for x86_64-unknown-linux-gnu
        run: cross build --target x86_64-unknown-linux-gnu
  build-i686-pc-windows-gnu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cross
        run: cargo install cross
      - name: Cross compile for i686-pc-windows-gnu
        run: cross build --features windows-build --target i686-pc-windows-gnu
  build-i686-unknown-linux-gnu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cross
        run: cargo install cross
      - name: Cross compile for i686-unknown-linux-gnu
        run: cross build --target i686-unknown-linux-gnu
  build-aarch64-pc-windows-gnullvm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cross
        run: cargo install cross
      - name: Cross compile for aarch64-pc-windows-gnullvm
        run: cross build --features windows-build --target aarch64-pc-windows-gnullvm
  build-aarch64-unknown-linux-gnu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cross
        run: cargo install cross
      - name: Cross compile for aarch64-unknown-linux-gnu
        run: cross build --target aarch64-unknown-linux-gnu

  build-aarch64-pc-windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Cargo compile for aarch64-pc-windows-msvc
        run: cargo build --features windows-build --target aarch64-pc-windows-msvc
  build-x86_64-pc-windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Cargo compile for x86_64-pc-windows-msvc
        run: cargo build --features windows-build --target x86_64-pc-windows-msvc
  build-i686-pc-windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Cargo compile for i686-pc-windows-msvc
        run: cargo build --features windows-build --target i686-pc-windows-msvc