name: cross compile

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-x86_64-pc-windows-gnu:
    runs-on: ubuntu-latest
    env:
      TARGET: x86_64-pc-windows-gnu
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cross
        run: cargo install cross
      - name: Cross compile for ${{ env.TARGET }}
        run: cross build --features windows-build --target ${{ env.TARGET }} --release
      - name: Rename compiled file
        run: mv target/${{ env.TARGET }}/release/matrix-onebot.exe target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}.exe
      - name: Get compiled file
        run: ls target/${{ env.TARGET }}/release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: matrix-onebot-${{ env.TARGET }}.exe
          path: target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}.exe
      - name: Release
        uses: softprops/action-gh-release@v2    
  build-x86_64-unknown-linux-gnu:
    runs-on: ubuntu-latest
    env:
      TARGET: x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cross
        run: cargo install cross
      - name: Cross compile for ${{ env.TARGET }}
        run: cross build --target ${{ env.TARGET }} --release
      - name: Rename compiled file
        run: mv target/${{ env.TARGET }}/release/matrix-onebot target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}
      - name: Get compiled file
        run: ls target/${{ env.TARGET }}/release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: matrix-onebot-${{ env.TARGET }}
          path: target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}
      - name: Release
        uses: softprops/action-gh-release@v2  
  build-i686-pc-windows-gnu:
    runs-on: ubuntu-latest
    env:
      TARGET: i686-pc-windows-gnu
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cross
        run: cargo install cross
      - name: Cross compile for ${{ env.TARGET }}
        run: cross build --features windows-build --target ${{ env.TARGET }} --release
      - name: Rename compiled file
        run: mv target/${{ env.TARGET }}/release/matrix-onebot.exe target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}.exe
      - name: Get compiled file
        run: ls target/${{ env.TARGET }}/release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: matrix-onebot-${{ env.TARGET }}.exe
          path: target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}.exe
      - name: Release
        uses: softprops/action-gh-release@v2       
  build-i686-unknown-linux-gnu:
    runs-on: ubuntu-latest
    env:
      TARGET: i686-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cross
        run: cargo install cross
      - name: Cross compile for ${{ env.TARGET }}
        run: cross build --target ${{ env.TARGET }} --release
      - name: Rename compiled file
        run: mv target/${{ env.TARGET }}/release/matrix-onebot target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}
      - name: Get compiled file
        run: ls target/${{ env.TARGET }}/release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: matrix-onebot-${{ env.TARGET }}
          path: target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}
      - name: Release
        uses: softprops/action-gh-release@v2       
  build-aarch64-unknown-linux-gnu:
    runs-on: ubuntu-latest
    env:
      TARGET: aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cross
        run: cargo install cross
      - name: Cross compile for ${{ env.TARGET }}
        run: cross build --target ${{ env.TARGET }} --release
      - name: Rename compiled file
        run: mv target/${{ env.TARGET }}/release/matrix-onebot target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}
      - name: Get compiled file
        run: ls target/${{ env.TARGET }}/release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: matrix-onebot-${{ env.TARGET }}
          path: target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}
      - name: Release
        uses: softprops/action-gh-release@v2        
  build-x86_64-pc-windows-msvc:
    runs-on: windows-latest
    env:
      TARGET: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Cargo compile for ${{ env.TARGET }}
        run: cargo build --features windows-build --target ${{ env.TARGET }} --release
      - name: Rename compiled file
        run: mv target/${{ env.TARGET }}/release/matrix-onebot.exe target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}.exe
      - name: Get compiled file
        run: ls target/${{ env.TARGET }}/release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: matrix-onebot-${{ env.TARGET }}.exe
          path: target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}.exe
      - name: Release
        uses: softprops/action-gh-release@v2       
  build-i686-pc-windows-msvc:
    runs-on: windows-latest
    env:
      TARGET: i686-pc-windows-msvc
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Cargo compile for ${{ env.TARGET }}
        run: cargo build --features windows-build --target ${{ env.TARGET }} --release
      - name: Rename compiled file
        run: mv target/${{ env.TARGET }}/release/matrix-onebot.exe target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}.exe
      - name: Get compiled file
        run: ls target/${{ env.TARGET }}/release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: matrix-onebot-${{ env.TARGET }}.exe
          path: target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}.exe
      - name: Release
        uses: softprops/action-gh-release@v2  
