name: cross compile

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: TODO New Release.
          draft: false
          prerelease: false
  build-x86_64-pc-windows-gnu:
    runs-on: ubuntu-latest
    env:
      TARGET: x86_64-pc-windows-gnu
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cross
        run: cargo install cross
      - name: Cross compile for ${{ env.TARGET }}
        run: cross build --features windows-build --target ${{ env.TARGET }}
      - name: Rename compiled file
        run: mv target/${{ env.TARGET }}/release/matrix-onebot.exe target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}.exe
      - name: Get compiled file
        run: ls target/${{ env.TARGET }}/release
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create-release.outputs.tag_name }}
          files: target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}.exe
  build-x86_64-unknown-linux-gnu:
    runs-on: ubuntu-latest
    env:
      TARGET: x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cross
        run: cargo install cross
      - name: Cross compile for ${{ env.TARGET }}
        run: cross build --target ${{ env.TARGET }}
      - name: Rename compiled file
        run: mv target/${{ env.TARGET }}/release/matrix-onebot target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}
      - name: Get compiled file
        run: ls target/${{ env.TARGET }}/release
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create-release.outputs.tag_name }}
          files: target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}
  build-i686-pc-windows-gnu:
    runs-on: ubuntu-latest
    env:
      TARGET: i686-pc-windows-gnu
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cross
        run: cargo install cross
      - name: Cross compile for ${{ env.TARGET }}
        run: cross build --features windows-build --target ${{ env.TARGET }}
      - name: Rename compiled file
        run: mv target/${{ env.TARGET }}/release/matrix-onebot.exe target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}.exe
      - name: Get compiled file
        run: ls target/${{ env.TARGET }}/release
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create-release.outputs.tag_name }}
          files: target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}.exe
  build-i686-unknown-linux-gnu:
    runs-on: ubuntu-latest
    env:
      TARGET: i686-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cross
        run: cargo install cross
      - name: Cross compile for ${{ env.TARGET }}
        run: cross build --target ${{ env.TARGET }}
      - name: Rename compiled file
        run: mv target/${{ env.TARGET }}/release/matrix-onebot target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}
      - name: Get compiled file
        run: ls target/${{ env.TARGET }}/release
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create-release.outputs.tag_name }}
          files: target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}
  build-aarch64-unknown-linux-gnu:
    runs-on: ubuntu-latest
    env:
      TARGET: aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Install cross
        run: cargo install cross
      - name: Cross compile for ${{ env.TARGET }}
        run: cross build --target ${{ env.TARGET }}
      - name: Rename compiled file
        run: mv target/${{ env.TARGET }}/release/matrix-onebot target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}
      - name: Get compiled file
        run: ls target/${{ env.TARGET }}/release
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create-release.outputs.tag_name }}
          files: target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}
  build-x86_64-pc-windows-msvc:
    runs-on: windows-latest
    env:
      TARGET: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Cargo compile for ${{ env.TARGET }}
        run: cargo build --features windows-build --target ${{ env.TARGET }}
      - name: Rename compiled file
        run: mv target/${{ env.TARGET }}/release/matrix-onebot.exe target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}.exe
      - name: Get compiled file
        run: ls target/${{ env.TARGET }}/release
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create-release.outputs.tag_name }}
          files: target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}.exe
  build-i686-pc-windows-msvc:
    runs-on: windows-latest
    env:
      TARGET: i686-pc-windows-msvc
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Cargo compile for ${{ env.TARGET }}
        run: cargo build --features windows-build --target ${{ env.TARGET }}
      - name: Rename compiled file
        run: mv target/${{ env.TARGET }}/release/matrix-onebot.exe target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}.exe
      - name: Get compiled file
        run: ls target/${{ env.TARGET }}/release
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create-release.outputs.tag_name }}
          files: target/${{ env.TARGET }}/release/matrix-onebot-${{ env.TARGET }}.exe